name: Render Video

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Video title'
        required: false
        default: 'Hello World'
        type: string
      subtitle:
        description: 'Video subtitle'
        required: false
        default: 'Welcome to Remotion'
        type: string
      content_header:
        description: 'Content section header'
        required: false
        default: 'Discover More'
        type: string
      outro_message:
        description: 'Outro message'
        required: false
        default: 'Thank You!'
        type: string


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  render-video:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create output directory
      run: mkdir -p ./output

    - name: Run video render container
      run: |
        docker run --rm \
          -v $(pwd)/output:/usr/src/app/out \
          -e TITLE="${{ github.event.inputs.title || 'Hello World' }}" \
          -e SUBTITLE="${{ github.event.inputs.subtitle || 'Welcome to Remotion' }}" \
          -e CONTENT_HEADER="${{ github.event.inputs.content_header || 'Discover More' }}" \
          -e OUTRO_MESSAGE="${{ github.event.inputs.outro_message || 'Thank You!' }}" \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main

    - name: List output files
      run: ls -la ./output/

    - name: Upload video as artifact
      uses: actions/upload-artifact@v4
      with:
        name: rendered-video
        path: ./output/
        retention-days: 30

    - name: Create release with video
      if: github.event_name == 'workflow_dispatch'
      uses: softprops/action-gh-release@v1
      with:
        files: ./output/*.mp4
        tag_name: video-${{ github.run_number }}
        name: "Video Render ${{ github.run_number }}"
        body: |
          Video rendered with parameters:
          - Title: ${{ github.event.inputs.title || 'Hello World' }}
          - Subtitle: ${{ github.event.inputs.subtitle || 'Welcome to Remotion' }}
          - Content Header: ${{ github.event.inputs.content_header || 'Discover More' }}
          - Outro Message: ${{ github.event.inputs.outro_message || 'Thank You!' }}
          
          Rendered at: ${{ github.event.head_commit.timestamp }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 